# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0002_publisher_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='pub_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='pub_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='pub_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='pub_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='logo',
        ),
    ]
