# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0006_publisher_popularity_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='traffic',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
